Add location info in message and contributor in README
xofbd/wqu_project_s202009 pull request #11
Opened 2020-11-22 20:39 UTC by turbatuandrei

Pull request to solve issue:
https://github.com/xofbd/wqu_project_s202009/issues/1

2020-11-22 20:43 UTC, turbatuandrei commented
@xofbd could you take a look at this?

2020-11-23 01:19 UTC, xofbd requested changes
A couple of minor changes before we can merge.

2020-11-23 01:19 UTC, xofbd commented on wqu_app/message.py
> +    city = get_geolocation(ip_address)[1]
Notice how we are calling `get_geolocation` function twice? We can combine those two calls into one.

2020-11-23 01:19 UTC, xofbd commented on wqu_app/message.py
> +    return f"Hello, the temperature in {city}(where your internet provider is located) is {temperature} deg C"
I would have the parenthetical statement to be `(based on your IP address)`.

2020-11-25 16:41 UTC, xofbd approved these changes

2020-11-25 16:41 UTC, merged